DROP TABLE IF EXISTS accounts;

DROP TABLE IF EXISTS actors;
DROP TYPE IF EXISTS ACTOR_TYPE;

DROP TABLE IF EXISTS account_keys;
DROP TABLE IF EXISTS note_sources;
DROP TABLE IF EXISTS notes;

DROP TABLE IF EXISTS follows;